#/bin/bash

#$ -cwd
#$ -S /bin/bash
#$ -pe smp 7
#$ -l mf=30G
#$ -N nom_treball
#$ -e nom_arx_errors
#$ -o nom_arx_sortida
#$ -t 1-100
#$ -tc 15

# Please note that this was done before submission


set -e
quality=20



options=options.txt
source $(echo $options)



########################################
#######   5_Kraken + braken       #######
########################################


# Load modules

module load apps/kraken2-2.1.2
module load apps/bracken-2.2

#Classify reads with kraken2


mkdir -p temp/5_kraken

mkdir -p temp/5_kraken/1_kraken2

mkdir -p temp/5_kraken/1_kraken2/k2_outputs
mkdir -p temp/5_kraken/1_kraken2/k2_reports




## 5.1_generacio_list_fw_rv.txt
#################################################################################


for i in temp/3_dedup_trim/seq_output/*m1.fq ; do
  echo "$(realpath "$i")";
 done > temp/5_kraken/1_kraken2/5_list_forward_qc.txt

sleep 10

for i in temp/3_dedup_trim/seq_output/*m2.fq ; do
   echo "$(realpath "$i")";
done > temp/5_kraken/1_kraken2/5_list_reverse_qc.txt


sleep 10


## 5.2_unio_list_fw_rv.txt. 
#################################################################################
## Crear un txt amb la info de list_forward_sf + list_reverse. Dins aquesta mateixa carpeta:

paste -d ' ' temp/5_kraken/1_kraken2/5_list_forward_qc.txt temp/5_kraken/1_kraken2/5_list_reverse_qc.txt > temp/5_kraken/1_kraken2/5_filelist.txt



sleep 30




## 5.1_KRAKEN
##############################################################################


filelist_5=temp/5_kraken/1_kraken2/5_filelist.txt
m5=$(sed "${SGE_TASK_ID}q;d" $filelist_5 | cut -d ' ' -f1)
m6=$(sed "${SGE_TASK_ID}q;d" $filelist_5 | cut -d ' ' -f2)

fname=$(echo $m5 | awk -F "/" '{print $NF}' | cut -f1 -d "." | sed 's/R1//')


kraken2 --db ${kraken_database}/ \
  --confidence 0.1 \
  --threads 24 \
  --use-names \
  --output ${out5}/${fname}output.txt \
  --report ${rep5}/${fname}report.txt \
  --paired $m5 $m6



