#/bin/bash

#$ -cwd
#$ -S /bin/bash
#$ -pe smp 8
#$ -l mf=28G
#$ -N nom_treball
#$ -e nom_arx_errors
#$ -o nom_arx_sortida

# Load modules

module load apps/kraken2-2.1.2
module load apps/bracken-2.2
set -e
quality=20



options=options.txt
source $(echo $options)


## 5.4_krakentools_2 - species
##############################################################################

## Unió de tots els fitxers de cada mostra en un

mkdir -p out


# SPECIE

python ./combine_mpa.py -i */temp/5_kraken/2_braken/species/mpa/*_mpa.txt -o out/combined_species_mpa.txt
grep -E "(s__)|(#Classification)" out/combined_species_mpa.txt > out/bracken_abundance_species_mpa.txt










