#/bin/bash

#$ -cwd
#$ -S /bin/bash
#$ -pe smp 5
#$ -l mf=20G
#$ -N nom_treball
#$ -e nom_arx_errors
#$ -o nom_arx_sortida
#$ -t 1-100
#$ -tc 15

# Please note that this was done before submission

module load apps/java-9.0.4
module load apps/bowtie2-2.3.4
module load apps/samtools-1.8
module load apps/bbmap-38.26


set -e
quality=20


options=options.txt
source $(echo $options)


########################################
########    1_human_remove       #######
########################################

mkdir -p temp/1_human_remove


## 1.1_generacio_list_fw_rv.txt
#################################################################################



if [ ! -e "temp/1_human_remove/1_list_forward_sg.txt" ]; then
  for i in ${raw}/*/*_1.* ; do
    # Utiliza 'realpath' para obtener la ruta completa del archivo
    echo "$(realpath "$i")";
  done > temp/1_human_remove/1_list_forward_sg.txt
fi


sleep 30

if [ ! -e "temp/1_human_remove/1_list_reverse_sg.txt" ]; then
  for i in ${raw}/*/*_2.* ; do
    # Utiliza 'realpath' para obtener la ruta completa del archivo
    echo "$(realpath "$i")";
  done > temp/1_human_remove/1_list_reverse_sg.txt
fi


sleep 30


## 1.2_unio_list_fw_rv.txt. 
#################################################################################
## Crear un txt amb la info de list_forward_sf + list_reverse. Dins aquesta mateixa carpeta:



paste -d ' ' temp/1_human_remove/1_list_forward_sg.txt temp/1_human_remove/1_list_reverse_sg.txt > temp/1_human_remove/1_filelist.txt

sleep 30


## 1.3_sub_remove_human.txt
#################################################################################



mkdir -p temp/1_human_remove/nohuman
mkdir -p temp/1_human_remove/human



filelist_1=temp/1_human_remove/1_filelist.txt



m1=$(sed "${SGE_TASK_ID}q;d" $filelist_1 | cut -d ' ' -f1)
m2=$(sed "${SGE_TASK_ID}q;d" $filelist_1 | cut -d ' ' -f2)
id=$(echo $m1 | awk -F "/" '{print $NF}' | cut -f1 -d "." | sed 's/_R1//')




bowtie2 \
    -x /mnt/typhon/references/human/hg38/ncbi/indexes/bowtie2/genome \
    -p 8 \
    -1 ${m1} \
    -2 ${m2} \
    -S ${temp1}/${id}_human.sam \
    --very-sensitive-local \
    -k 1




samtools fastq -@ 8 \
    -1 ${out1}/${id}_nohuman.m1.fq \
    -2 ${out1}/${id}_nohuman.m2.fq \
    -f 12 ${temp1}/${id}_human.sam
