#!/bin/bash

#SBATCH --job-name=post_qc
#SBATCH --mem=40G
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=8
#SBATCH --output=post_qc.txt
#SBATCH --error=post_qc.txt
#SBATCH --chdir=.
##SBATCH --array=1-2%2

set -e
quality=20


options=options.txt
source $(echo $options)


########################################
#####   4_QC_FASTQC_after_trim    #####
########################################

mkdir -p temp/4_QC_after_trim



## 4.1_obtaining_fastqchtml
#################################################################################
## Load modules

module load apps/fastqc/0.12.1
fastqc -t 24 temp/3_dedup_trim/seq_output/* --outdir temp/4_QC_after_trim/


## 4.2_MultiQC_aplication
#################################################################################

## Merging all reports generated by `1_obtaining_fastqchtml.R` with MultiQC

## Load the MultiQC module
module load apps/multiqcapps/multiqc/1.25.1


#Generate the MultiQC report
multiqc temp/4_QC_after_trim --outdir temp/4_QC_after_trim
module unload  apps/multiqcapps/multiqc/1.25.1



